name: PRGminer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - biopython=1.81
  - pandas=2.1.0
  - numpy=1.24.0
  - scikit-learn=1.3.0
  - scipy=1.11.0
  - h5py=3.9.0
  - git-lfs
  # setuptools<81 is required because tensorflow-macos 2.13.0 depends on
  # tensorboard 2.13.0, which uses pkg_resources (removed in setuptools>=81).
  # See: https://setuptools.pypa.io/en/latest/pkg_resources.html
  - setuptools<81
  - pip:
    - tensorflow==2.13.0
    - keras==2.13.1
    - xlrd==2.0.1
    - openpyxl==3.1.2
    - matplotlib==3.7.2
    - seaborn==0.12.2
    - plotly==5.16.1
    - joblib==1.3.2
    - tqdm==4.66.1
    - pytest==7.4.2
    - black==23.9.1
    - flake8==6.1.0
    - mypy==1.5.1
    - pip install .
    